<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Redactor.aspx.cs" Inherits="Redactor" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Untitled Page</title>
</head>
<body>
    <form id="form1" runat="server">
    <div align="center">
    
        <asp:Calendar ID="cdViewer" runat="server" BackColor="White" 
            BorderColor="#999999" CellPadding="4" DayNameFormat="Shortest" 
            FirstDayOfWeek="Monday" Font-Names="Verdana" Font-Size="8pt" ForeColor="Black" 
            Height="180px" Width="200px" 
            onselectionchanged="cdViewer_SelectionChanged">
            <SelectedDayStyle BackColor="#666666" Font-Bold="True" ForeColor="White" />
            <SelectorStyle BackColor="#CCCCCC" />
            <WeekendDayStyle BackColor="#FFFFCC" />
            <TodayDayStyle BackColor="#CCCCCC" ForeColor="Black" />
            <OtherMonthDayStyle ForeColor="#808080" />
            <NextPrevStyle VerticalAlign="Bottom" />
            <DayHeaderStyle BackColor="#CCCCCC" Font-Bold="True" Font-Size="7pt" />
            <TitleStyle BackColor="#999999" BorderColor="Black" Font-Bold="True" />
        </asp:Calendar>
        <asp:Button ID="btnShow" runat="server" Text="Показать отсутствия" 
            onclick="btnShow_Click" />
    
        <br />
        <asp:TextBox ID="tbReason" runat="server" Width="71px"></asp:TextBox>
        <asp:TextBox ID="tbHours" runat="server" Width="75px"></asp:TextBox>
        <asp:Button ID="btnChange" runat="server" Enabled="False" 
            onclick="btnChange_Click" style="height: 26px" Text="Изменить" />
    
        <br />
        <br />
        <br />
        <asp:Button ID="btnChangePupil" runat="server" onclick="Button1_Click" 
            Text="Сменить ученика" />
        <br />
        <br />
        <br />
        <asp:DropDownList ID="ddlHour" runat="server" Visible="False">
            <asp:ListItem>1</asp:ListItem>
            <asp:ListItem>2</asp:ListItem>
        </asp:DropDownList>
        <asp:DropDownList ID="ddlSubject" runat="server" DataSourceID="SqlDataSourceGetAllSubjects" 
            DataTextField="subject" DataValueField="subject" Visible="False">
        </asp:DropDownList>
        <asp:DropDownList ID="ddlValue" runat="server" Visible="False">
            <asp:ListItem></asp:ListItem>
            <asp:ListItem Value="1">1</asp:ListItem>
            <asp:ListItem>2</asp:ListItem>
            <asp:ListItem>3</asp:ListItem>
            <asp:ListItem>4</asp:ListItem>
            <asp:ListItem>5</asp:ListItem>
            <asp:ListItem>6</asp:ListItem>
            <asp:ListItem>7</asp:ListItem>
            <asp:ListItem>8</asp:ListItem>
            <asp:ListItem>9</asp:ListItem>
            <asp:ListItem>10</asp:ListItem>
            <asp:ListItem>11</asp:ListItem>
            <asp:ListItem>12</asp:ListItem>
        </asp:DropDownList>
        <asp:Button ID="btnRowEditAccept" runat="server" Text="OK" Visible="False" 
            onclick="btnRowEditAccept_Click" style="height: 26px" />
        <asp:Button ID="btnRowEditCancel" runat="server" Text="Отмена" 
            Visible="False" onclick="btnRowEditCancel_Click" />
    
    </div>
    <asp:GridView ID="gvView" runat="server" AutoGenerateDeleteButton="True" 
        AutoGenerateEditButton="True" onrowediting="gvView_RowEditing" 
        onselectedindexchanged="gvView_SelectedIndexChanged" 
        onrowdeleting="gvView_RowDeleting">
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSourceGetAllSubjects" runat="server" 
        ConnectionString="<%$ ConnectionStrings:SCSDataBaseRedactorConnectionString %>" 
        SelectCommand="getAllSubjects" SelectCommandType="StoredProcedure">
    </asp:SqlDataSource>
    <asp:Button ID="btnAddValues" runat="server" onclick="btnAddValues_Click" 
        Text="Добавить оценки" Visible="False" />
    <br />
    <br />
    <br />
    <br />
    <p>
        <asp:Button ID="btnBackToCabinet" runat="server" 
            onclick="btnBackToCabinet_Click" Text="Назад" />
        <asp:GridView ID="gvHidden" runat="server" Visible="False">
        </asp:GridView>
    </p>
    </form>
</body>
</html>
